### ISSUE TITLE
Updates? github project URL, CPAN release

### ISSUE THREAD

**Issue by mohawk2** [niner/inline-python-pm#3]
Seems to me that the project github URL justifies a CPAN release.

By the way, the project's "blurb" links to v0.28, which is no longer latest? How about linking to this? https://metacpan.org/release/Inline-Python

**Comment by zmughal** [comment]
The changes since the issue was opened also warrant a release. Here with Python 3.10.6 the tests for the [current CPAN release](https://metacpan.org/release/NINE/Inline-Python-0.56) almost all fail whereas the code in the repo works.

**Comment by niner** [comment]
Released version 0.57 to CPAN

**Comment by zmughal** [comment]
New release works great and thank you!
